# Dockerfile.dev (para desenvolvimento)
FROM node:22

WORKDIR /app

# Copia apenas package.json e instala dependências
COPY package*.json ./
RUN npm install --legacy-peer-deps

RUN npx puppeteer install chrome

# Para Debian/Ubuntu
RUN apt-get update && apt-get install -y \
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget \
 && rm -rf /var/lib/apt/lists/*

# Exponha a porta usada pelo Nest
EXPOSE 3000

# Comando padrão (modo dev + host 0.0.0.0)
CMD ["npm", "run", "start:dev"]
